---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: latest
    update_cache: yes

- name: Copy fail2ban config
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: preserve

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted