---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy ssl crt
  copy:
    src: lbess.ru.crt
    dest: /etc/ssl/lbess.ru.crt
    mode: preserve

- name: Copy ssl conf
  copy:
    src: lbess.ru.key
    dest: /etc/ssl/lbess.ru.key
    mode: preserve

- name: Copy nginx config
  copy:
    src: api.conf
    dest: /etc/nginx/conf.d/api.conf
    mode: preserve

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
