---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy nginx config
  copy:
    src: api.conf
    dest: /etc/nginx/conf.d/api.conf
    mode: preserve

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
